module.exports = {
  site: {
    name: "Clickie",
    url: "https://clickie.io/",
    homePath: "index.html",
    blogIndexPath: "recursos/blog.html",
    guidesIndexPath: "recursos/guias.html",
    defaultOgImage: "assets/logo-clickie-web.png",
    publisherLogo: "assets/logo-clickie-web.png",
    contactEmail: "hola@clickie.io",
    linkedinUrl: "https://www.linkedin.com/company/onclickie",
    xUrl: "https://x.com/onclickie",
    ctaTitle: "¿Quieres implementar estas estrategias en tu negocio?",
    ctaBody: "Nuestros expertos te ayudan a diseñar un plan de eficiencia energética a medida.",
    ctaPrimaryLabel: "Hablar con un experto",
    ctaPrimaryPath: "index.html#contacto",
    ctaSecondaryLabel: "Ver más artículos",
    ctaSecondaryPath: "recursos/blog.html"
  },
  categories: [
    { key: "all", label: "Todos" },
    { key: "eficiencia", label: "Eficiencia Energética" },
    { key: "multisucursal", label: "Multisucursal" },
    { key: "casos", label: "Casos de Éxito" },
    { key: "industria", label: "Industria" },
    { key: "sostenibilidad", label: "Sostenibilidad" },
    { key: "prensa", label: "Prensa" }
  ],
  posts: [
    {
      slug: "tu-sistema-hvac-no-esta-roto-esta-gastando-el-doble-para-ocultar-que-perdio-el-control",
      sourceFile: "content/blog-posts/tu-sistema-hvac-no-esta-roto-esta-gastando-el-doble-para-ocultar-que-perdio-el-control.source",
      title: "Tu sistema HVAC no está roto: está gastando el doble para ocultar que perdió el control",
      subtitle: "Cuando la operación normaliza la deriva térmica, la climatización empieza a comprar estabilidad con sobreconsumo, demanda punta y desgaste acelerado.",
      description: "La mayor parte de los sobrecostos HVAC no nace en una falla del equipo, sino en la pérdida de gobernanza sobre horarios, setpoints y desvíos operativos.",
      categoryKey: "multisucursal",
      publishedAt: "2026-08-06",
      coverImage: "assets/blog/tu-sistema-hvac-no-esta-roto-cover.png",
      coverAlt: "Bloques azules desalineados que representan la deriva y la pérdida de control en un sistema HVAC"
    },
    {
      slug: "sin-revision-mensual-activa-tu-sistema-de-gestion-energetica-genera-reportes-pero-no-ahorros",
      sourceFile: "content/blog-posts/sin-revision-mensual-activa-tu-sistema-de-gestion-energetica-genera-reportes-pero-no-ahorros.source",
      title: "Sin revisión mensual activa, tu sistema de gestión energética genera reportes, pero no ahorros",
      subtitle: "La diferencia entre un panel cargado de datos y un 15% de ahorro real no está en la plataforma: está en la intervención humana.",
      description: "Acumular datos energéticos sin revisión mensual activa solo genera reportes presentables. El ahorro real aparece cuando hay análisis, priorización e intervención humana.",
      categoryKey: "eficiencia",
      publishedAt: "2026-08-06",
      coverImage: "assets/blog/revision-mensual-gestion-energetica-cover.jpg",
      coverAlt: "Equipo de Clickie junto a un tablero de monitoreo energético durante una jornada en terreno"
    },
    {
      slug: "presupuesto-energetico-no-es-un-bloque-fijo",
      sourceFile: "content/blog-posts/presupuesto-energetico-no-es-un-bloque-fijo.source",
      title: "Tu presupuesto energético no es un bloque fijo: por qué romper la estimación lineal evita sorpresas",
      subtitle: "Presupuestar energía como una partida fija oculta volatilidad operativa, distorsiona el margen y vuelve reactiva la conversación entre Finanzas y Operaciones.",
      description: "Tratar la energía como un costo fijo debilita cualquier presupuesto. Descubre cómo modelarla por capas para evitar desvíos y proteger margen.",
      categoryKey: "eficiencia",
      publishedAt: "2026-08-04",
      coverImage: "assets/blog/presupuesto-energetico-no-es-un-bloque-fijo-cover.png",
      coverAlt: "Barras abstractas representando un presupuesto energético con variaciones y desvíos"
    },
    {
      slug: "benchmark-energetico-multisucursal-comparar-sucursales-sin-castigar-al-local-equivocado",
      sourceFile: "content/blog-posts/benchmark-energetico-multisucursal-comparar-sucursales-sin-castigar-al-local-equivocado.source",
      title: "Benchmark energético multisucursal: cómo segmentar la red sin castigar al local equivocado",
      subtitle: "La comparación útil no ordena por consumo bruto: agrupa por clúster operativo para asignar mantenimiento, auditorías y CAPEX con mejor criterio.",
      description: "Un benchmark útil no compara sucursales en bruto: segmenta la red para priorizar presupuesto, mantenimiento y CAPEX donde realmente importa.",
      categoryKey: "multisucursal",
      publishedAt: "2026-07-27",
      coverImage: "assets/blog/benchmark-energetico-multisucursal-comparar-sucursales-sin-castigar-al-local-equivocado-cover.png",
      coverAlt: "Sucursales de distintos formatos equilibradas en una balanza para representar un benchmark energético justo"
    },
    {
      slug: "aqui-van-algunas-mezclas-el-alza-de-julio-carga-el-84-al-sector-comercial-esta-tu-operacion-lista",
      sourceFile: "content/blog-posts/aqui-van-algunas-mezclas-el-alza-de-julio-carga-el-84-al-sector-comercial-esta-tu-operacion-lista.source",
      title: "El alza de julio carga el 84% al sector comercial: ¿está tu operación lista?",
      subtitle: "La baja del primer semestre fue transitoria: julio concentra ajustes, descongelamientos y nuevos contratos que golpean especialmente a la operación comercial.",
      description: "Julio concentra los mayores cambios tarifarios del año para el sector comercial. Entiende qué está subiendo y cómo prepararte con datos por local.",
      categoryKey: "multisucursal",
      publishedAt: "2026-07-14",
      coverImage: "assets/blog/que-va-a-pasar-con-tu-factura-electrica-en-2026-cover.jpg",
      coverAlt: "Persona revisando una factura frente a una pantalla con análisis energético"
    },
    {
      slug: "esg-datos-reales-trazabilidad-energia",
      sourceFile: "content/blog-posts/esg-datos-reales-trazabilidad-energia.source",
      title: "ESG con datos reales: por qué una factura no alcanza para reportar energía, agua y gas",
      subtitle: "Para reportar bien energía, agua y gas no basta con juntar facturas: hace falta trazabilidad por sucursal, dato confiable y criterio operativo.",
      description: "Un buen reporte ESG necesita trazabilidad real, no solo consolidación de facturas. Descubre cómo mejorar la calidad del dato energético e hídrico.",
      categoryKey: "sostenibilidad",
      publishedAt: "2026-07-14",
      coverImage: "assets/blog/esg-datos-reales-trazabilidad-energia-cover.jpg",
      coverAlt: "ESG con datos reales: por qué una factura no alcanza para reportar energía, agua y gas"
    },
    {
      slug: "que-hacen-distinto-los-lideres-en-sostenibilidad",
      sourceFile: "content/blog-posts/que-hacen-distinto-los-lideres-en-sostenibilidad.source",
      title: "Qué hacen distinto los líderes en sostenibilidad",
      subtitle: "Medición rigurosa, planes claros y digitalización distinguen a las empresas que convierten sostenibilidad en ventaja competitiva.",
      description: "Un estudio de Boston Consulting Group muestra qué tienen en común las empresas que avanzan mejor en sostenibilidad y crecimiento.",
      categoryKey: "sostenibilidad",
      publishedAt: "2026-07-14",
      coverImage: "assets/blog/edificios-verdes-y-monitoreo-de-energia-con-clickie-cover.jpg",
      coverAlt: "Vista aérea de edificios sostenibles y urbanismo verde"
    },
    {
      slug: "equipos-que-funcionan-pero-ya-estan-fallando-lo-que-la-curva-de-energia-detecta-antes-del-service",
      sourceFile: "content/blog-posts/equipos-que-funcionan-pero-ya-estan-fallando-lo-que-la-curva-de-energia-detecta-antes-del-service.source",
      title: "Equipos que funcionan, pero ya están fallando: lo que la curva de energía detecta antes del service",
      subtitle: "Leer la energía como señal de salud del activo permite anticipar fallas, ordenar mantenimiento y evitar sobrecostos invisibles.",
      description: "La curva de energía puede anticipar fallas antes del service. Aprende a detectar desvíos tempranos y a intervenir antes de una avería mayor.",
      categoryKey: "industria",
      publishedAt: "2026-07-06",
      coverImage: "assets/blog/equipos-que-funcionan-pero-ya-estan-fallando-lo-que-la-curva-de-energia-detecta-antes-del-service-cover.png",
      coverAlt: "Equipos que funcionan, pero ya están fallando: lo que la curva de energía detecta antes del service"
    },
    {
      slug: "prorrateos-a-ciegas-la-ineficiencia-energetica-que-los-centros-comerciales-mall",
      sourceFile: "content/blog-posts/prorrateos-a-ciegas-la-ineficiencia-energetica-que-los-centros-comerciales-mall.source",
      title: "Prorrateos con baja visibilidad: cómo identificar desvíos energéticos en locales dentro de centros comerciales",
      subtitle: "Cuando un local opera dentro de un centro comercial, la falta de medición directa puede esconder sobrecostos y desvíos difíciles de auditar.",
      description: "Operar dentro de un mall puede ocultar sobrecostos eléctricos. Aprende a detectar desvíos y a auditar prorrateos con mejor criterio energético.",
      categoryKey: "multisucursal",
      publishedAt: "2026-06-23",
      coverImage: "assets/blog/prorrateos-a-ciegas-la-ineficiencia-energetica-que-los-centros-comerciales-mall-cover.png",
      coverAlt: "Prorrateos con baja visibilidad: cómo identificar desvíos energéticos en locales dentro de centros comerciales"
    },
    {
      slug: "tarifa-electrica-operacion-real",
      sourceFile: "content/blog-posts/tarifa-electrica-operacion-real.source",
      title: "Cómo saber si tu tarifa eléctrica dejó de calzar con tu operación",
      subtitle: "Una tarifa que antes calzaba puede quedar obsoleta cuando cambian horarios, demanda y perfil de carga de la operación.",
      description: "Tu tarifa eléctrica puede dejar de ser conveniente sin que nadie lo note. Revisa cómo detectar cuando el contrato ya no calza con tu operación.",
      categoryKey: "eficiencia",
      publishedAt: "2026-06-16",
      coverImage: "assets/blog/tarifa-electrica-operacion-real-cover.png",
      coverAlt: "Cómo saber si tu tarifa eléctrica dejó de calzar con tu operación"
    },
    {
      slug: "consumo-nocturno-retail-multisucursal",
      sourceFile: "content/blog-posts/consumo-nocturno-retail-multisucursal.source",
      title: "Consumo nocturno en retail multisucursal: el costo que sigue corriendo cuando el local ya cerró",
      subtitle: "La noche revela cargas residuales, automatizaciones fuera de horario y desvíos que, multiplicados por sucursal, erosionan el margen sin hacer ruido.",
      description: "El consumo nocturno puede esconder una fuga estructural en cadenas multisucursal. Aprende a leer la noche como una línea base de control.",
      categoryKey: "multisucursal",
      publishedAt: "2026-06-10",
      coverImage: "assets/blog/consumo-nocturno-retail-multisucursal-cover.png",
      coverAlt: "Consumo nocturno en retail multisucursal: el costo que sigue corriendo cuando el local ya cerró"
    },
    {
      slug: "benchmark-energetico-en-retail-por-que-no-todos-los-locales-deberian-medirse-igual",
      sourceFile: "content/blog-posts/benchmark-energetico-en-retail-por-que-no-todos-los-locales-deberian-medirse-igual.source",
      title: "Benchmark energético en retail: por qué no todos los locales deberían medirse igual",
      subtitle: "Farmacias, tiendas por departamento y cafeterías no consumen igual: comparar sin contexto lleva a metas erradas y decisiones pobres.",
      description: "Comparar consumo sin contexto puede distorsionar cualquier programa de eficiencia. Descubre cómo construir benchmarks útiles por formato de tienda.",
      categoryKey: "multisucursal",
      publishedAt: "2026-06-08",
      coverImage: "assets/blog/benchmark-energetico-en-retail-por-que-no-todos-los-locales-deberian-medirse-igual-cover.jpeg",
      coverAlt: "Benchmark energético en retail: por qué no todos los locales deberían medirse igual"
    },
    {
      slug: "verdantix-smart-innovators-2025-que-cambio-en-el-ems-moderno",
      sourceFile: "content/blog-posts/verdantix-smart-innovators-2025-que-cambio-en-el-ems-moderno.source",
      title: "Verdantix Smart Innovators 2025: qué cambió en el EMS moderno",
      subtitle: "El EMS ya no compite solo por visualizar consumo, sino por automatizar decisiones, integrarse a la operación y escalar con impacto real.",
      description: "El EMS moderno dejó de ser un dashboard. Revisa qué cambió en 2025 según Verdantix y cómo evaluar plataformas con criterio operativo.",
      categoryKey: "eficiencia",
      publishedAt: "2026-05-18",
      coverImage: "assets/blog/verdantix-smart-innovators-2025-que-cambio-en-el-ems-moderno-cover.png",
      coverAlt: "Verdantix Smart Innovators 2025: qué cambió en el EMS moderno"
    },
    {
      slug: "los-4-errores-que-esconde-una-factura-electrica-de-retail",
      sourceFile: "content/blog-posts/los-4-errores-que-esconde-una-factura-electrica-de-retail.source",
      title: "Los 4 errores que esconde una factura eléctrica de retail",
      subtitle: "Antes de invertir en tecnología, conviene revisar si la factura ya está arrastrando errores que se multiplican en cada local.",
      description: "En retail, los errores de facturación no escalan de forma lineal: se multiplican por sucursal. Aprende qué revisar antes de seguir pagando de más.",
      categoryKey: "multisucursal",
      publishedAt: "2026-05-11",
      coverImage: "assets/blog/los-4-errores-que-esconde-una-factura-electrica-de-retail-cover.jpg",
      coverAlt: "Los 4 errores que esconde una factura eléctrica de retail"
    },
    {
      slug: "alza-tarifaria-julio-2026-retailers-multisucursal",
      sourceFile: "content/blog-posts/alza-tarifaria-julio-2026-retailers-multisucursal.source",
      title: "Cómo prepararte para el alza tarifaria de julio de 2026: impacto del 10% en retailers multisucursal",
      subtitle: "El ajuste tarifario de julio de 2026 puede transformarse en un golpe de 6% a 10% para cadenas multisucursal si no se gestiona con datos por local.",
      description: "El alza tarifaria de julio 2026 impactará fuertemente a los retailers multisucursal, con aumentos reales de hasta el 10%. Descubre cómo prepararte.",
      categoryKey: "multisucursal",
      publishedAt: "2026-04-24",
      readingTime: 4,
      coverImage: "assets/blog/alza-tarifaria-julio-2026-retailers-multisucursal-cover.png",
      coverAlt: "Cómo prepararte para el alza tarifaria de julio de 2026: impacto del 10% en retailers multisucursal"
    },
    {
      slug: "como-las-tarifas-electricas-impactan-tu-operacion-diaria-y-que-hacer-para-pagar-menos",
      sourceFile: "content/blog-posts/como-las-tarifas-electricas-impactan-tu-operacion-diaria-y-que-hacer-para-pagar-menos.source",
      title: "Cómo las tarifas eléctricas impactan tu operación diaria (y qué hacer para pagar menos)",
      subtitle: "Picos de demanda, horarios y categoría tarifaria pueden encarecer una operación comercial mucho más de lo que parece.",
      description: "Las tarifas eléctricas afectan el costo operativo más de lo visible. Revisa cómo leer su impacto y qué ajustes ayudan a pagar menos.",
      categoryKey: "multisucursal",
      publishedAt: "2026-04-23",
      coverImage: "assets/blog/como-las-tarifas-electricas-impactan-tu-operacion-diaria-y-que-hacer-para-pagar-menos-cover.png",
      coverAlt: "Cómo las tarifas eléctricas impactan tu operación diaria (y qué hacer para pagar menos)"
    },
    {
      slug: "optimiza-tu-operacion-diaria-cada-decision-energetica-cuenta",
      sourceFile: "content/blog-posts/optimiza-tu-operacion-diaria-cada-decision-energetica-cuenta.source",
      title: "Optimiza tu operación diaria: cada decisión energética cuenta",
      subtitle: "Cuando la operación cotidiana no tiene visibilidad energética, pequeñas decisiones repetidas terminan erosionando el margen.",
      description: "La energía está en cada decisión diaria del local. Descubre cómo ganar visibilidad, reaccionar antes y reducir ineficiencias repetidas.",
      categoryKey: "multisucursal",
      publishedAt: "2026-04-16",
      coverImage: "assets/blog/optimiza-tu-operacion-diaria-cada-decision-energetica-cuenta-cover.png",
      coverAlt: "Optimiza tu operación diaria: cada decisión energética cuenta"
    },
    {
      slug: "el-problema-no-es-el-consumo-energetico-en-retail-es-la-falta-de-decisiones",
      sourceFile: "content/blog-posts/el-problema-no-es-el-consumo-energetico-en-retail-es-la-falta-de-decisiones.source",
      title: "El problema no es el consumo energético en retail. Es la falta de decisiones",
      subtitle: "En retail, el costo energético rara vez se explica solo por consumo: el verdadero problema suele ser no decidir a tiempo con datos por local.",
      description: "La energía dejó de ser un costo fijo en retail. Aprende por qué el problema no es solo cuánto consumes, sino cómo decides con esa información.",
      categoryKey: "multisucursal",
      publishedAt: "2026-04-07",
      coverImage: "assets/blog/el-problema-no-es-el-consumo-energetico-en-retail-es-la-falta-de-decisiones-cover.png",
      coverAlt: "El problema no es el consumo energético en retail. Es la falta de decisiones"
    },
    {
      slug: "que-va-a-pasar-con-tu-factura-electrica-en-2026",
      sourceFile: "content/blog-posts/que-va-a-pasar-con-tu-factura-electrica-en-2026.source",
      title: "¿Qué va a pasar con tu factura eléctrica en 2026?",
      subtitle: "El año eléctrico 2026 no se comporta parejo: entender qué cambia antes y después de julio es clave para anticipar impacto en la factura.",
      description: "Tu factura eléctrica en 2026 tendrá dos mitades muy distintas. Revisa qué cambia durante el año y cómo prepararte antes de julio.",
      categoryKey: "multisucursal",
      publishedAt: "2026-04-07",
      coverImage: "assets/blog/que-va-a-pasar-con-tu-factura-electrica-en-2026-cover.jpg",
      coverAlt: "¿Qué va a pasar con tu factura eléctrica en 2026?"
    },
    {
      slug: "remarcacion-submetering",
      sourceFile: "content/blog-posts/remarcacion-submetering.source",
      title: "Remarcación y Submetering: lo que no mides, lo subsidias",
      subtitle: "La submedición permite asignar costos reales, detectar consumos anómalos y convertir la energía en una variable gestionable.",
      description: "Descubre cómo la remarcación y el submetering permiten a las empresas identificar ineficiencias, asignar costos reales y optimizar su consumo.",
      categoryKey: "eficiencia",
      publishedAt: "2026-03-18",
      readingTime: 3,
      coverImage: "assets/blog-remarcacion.jpg",
      coverAlt: "Centro comercial con personas y actividad comercial",
      featured: true
    },
    {
      slug: "supermercados-energia",
      sourceFile: "content/blog-posts/supermercados-energia.source",
      title: "Supermercados 24/7: el margen se protege gestionando la energía",
      subtitle: "La visibilidad energética ayuda a cadenas 24/7 a controlar refrigeración, climatización, iluminación y calidad de energía sin perder rentabilidad.",
      description: "En supermercados, la energía es uno de los principales costos operativos. Descubre cómo la visibilidad energética protege la rentabilidad.",
      categoryKey: "multisucursal",
      publishedAt: "2026-03-11",
      readingTime: 4,
      coverImage: "assets/blog-supermercados.jpg",
      coverAlt: "Pasillo de supermercado con clientes y góndolas"
    },
    {
      slug: "costo-confort-tiendas",
      sourceFile: "content/blog-posts/costo-confort-tiendas.source",
      title: "El costo invisible del confort en tiendas por departamento",
      subtitle: "Cuando HVAC e iluminación se gestionan a ciegas, la energía termina erosionando márgenes que parecían sanos.",
      description: "Las grandes superficies son un campo de batalla para la rentabilidad. Descubre cómo la energía consume tus ganancias y cómo gestionarla.",
      categoryKey: "multisucursal",
      publishedAt: "2026-03-04",
      readingTime: 5,
      coverImage: "assets/blog-tiendas-departamento.jpg",
      coverAlt: "Tienda por departamento con empleados y zona de ventas"
    },
    {
      slug: "5-errores-gestion-energetica",
      sourceFile: "content/blog-posts/5-errores-gestion-energetica.source",
      title: "5 Errores Comunes en la Gestión Energética y Cómo Solucionarlos",
      subtitle: "Cinco errores frecuentes que frenan ahorros energéticos y cómo corregirlos con mejor visibilidad, segmentación y apoyo experto.",
      description: "Descubre los errores comunes en la gestión energética y cómo solucionarlos para optimizar el consumo y reducir costos con la ayuda de Clickie.",
      categoryKey: "multisucursal",
      publishedAt: "2024-10-03",
      readingTime: 4,
      coverImage: "assets/blog/5-errores-gestion-energetica-cover.png",
      coverAlt: "5 Errores Comunes en la Gestión Energética y Cómo Solucionarlos"
    },
    {
      slug: "5-niveles-de-madurez-en-la-gestion-energetica",
      sourceFile: "content/blog-posts/5-niveles-de-madurez-en-la-gestion-energetica.source",
      title: "5 Niveles de Madurez en la Gestión Energética",
      subtitle: "Medir, ordenar y actuar: así evoluciona una empresa desde no tener control hasta gestionar la energía como una ventaja competitiva.",
      description: "Descubre los cinco niveles de madurez en la gestión energética y cómo optimizar recursos y reducir costos en tu empresa de manera eficiente y sostenible.",
      categoryKey: "sostenibilidad",
      publishedAt: "2024-10-15",
      coverImage: "assets/blog/5-niveles-de-madurez-en-la-gestion-energetica-cover.jpeg",
      coverAlt: "5 Niveles de Madurez en la Gestión Energética"
    },
    {
      slug: "como-un-buen-uso-de-la-energia-puede-transformar-tu-negocio",
      sourceFile: "content/blog-posts/como-un-buen-uso-de-la-energia-puede-transformar-tu-negocio.source",
      title: "Día Mundial del Ahorro de Energía: Cómo tu empresa puede hacer la diferencia",
      subtitle: "Pequeñas decisiones operativas, mejor tecnología y datos confiables pueden convertir el ahorro energético en una práctica permanente.",
      description: "El 21 de octubre es el Día Mundial del Ahorro de Energía. Descubre cómo pequeñas acciones y soluciones como las de Clickie pueden optimizar el consumo energético de tu empresa, reducir costos y contribuir a un futuro sostenible.",
      categoryKey: "sostenibilidad",
      publishedAt: "2024-10-23",
      coverImage: "assets/blog/como-un-buen-uso-de-la-energia-puede-transformar-tu-negocio-cover.jpg",
      coverAlt: "Día Mundial del Ahorro de Energía: Cómo tu empresa puede hacer la diferencia"
    },
    {
      slug: "las-empresas-consumidoras-de-energia-estan-cambiando-las-reglas-del-juego-en-el-sector-energetico-entrevista-a-marcelo-llevenes-ceo-de-clickie",
      sourceFile: "content/blog-posts/las-empresas-consumidoras-de-energia-estan-cambiando-las-reglas-del-juego-en-el-sector-energetico-entrevista-a-marcelo-llevenes-ceo-de-clickie.source",
      title: "Entrevista a Marcelo Llévenes, CEO de Clickie",
      subtitle: "Una conversación sobre electrificación, regulación y el nuevo margen de decisión que hoy tienen las empresas consumidoras de energía.",
      description: "Entrevista con Marcelo Llévenes sobre cómo las nuevas tecnologías y la sostenibilidad están transformando el sector energético, empoderando a los consumidores y modernizando la regulación.",
      categoryKey: "prensa",
      publishedAt: "2025-01-08",
      coverImage: "assets/blog/las-empresas-consumidoras-de-energia-estan-cambiando-las-reglas-del-juego-en-el-sector-energetico-entrevista-a-marcelo-llevenes-ceo-de-clickie-cover.png",
      coverAlt: "Entrevista a Marcelo Llévenes, CEO de Clickie"
    },
    {
      slug: "como-ahorrar-energia-en-tu-tienda-y-reducir-costos-operativos",
      sourceFile: "content/blog-posts/como-ahorrar-energia-en-tu-tienda-y-reducir-costos-operativos.source",
      title: "Cómo ahorrar energía en tu tienda y reducir costos operativos",
      subtitle: "Cinco acciones concretas para bajar consumo en tiendas sin afectar experiencia, operación ni confort.",
      description: "Optimiza el consumo energético en tu tienda con estrategias simples para reducir costos operativos y contribuir al cuidado del medioambiente. Descubre cómo ahorrar energía de manera efectiva.",
      categoryKey: "multisucursal",
      publishedAt: "2025-03-14",
      coverImage: "assets/blog/como-ahorrar-energia-en-tu-tienda-y-reducir-costos-operativos-cover.jpeg",
      coverAlt: "Cómo ahorrar energía en tu tienda y reducir costos operativos"
    },
    {
      slug: "monitoreo-de-agua",
      sourceFile: "content/blog-posts/monitoreo-de-agua.source",
      title: "Monitoreo de Agua para un Reciclado Eficiente y Cumplimiento con la DGA",
      subtitle: "La trazabilidad del agua subterránea ya no es opcional: medir, transmitir y cumplir bien reduce riesgo regulatorio y mejora la gestión hídrica.",
      description: "Soluciones tecnológicas para el monitoreo y transmisión de extracciones de agua subterránea, asegurando el cumplimiento de la normativa DGA y promoviendo la sostenibilidad hídrica.",
      categoryKey: "sostenibilidad",
      publishedAt: "2025-03-14",
      coverImage: "assets/blog/monitoreo-de-agua-cover.jpeg",
      coverAlt: "Monitoreo de Agua para un Reciclado Eficiente y Cumplimiento con la DGA"
    },
    {
      slug: "la-hora-del-planeta-mas-que-apagar-las-luces",
      sourceFile: "content/blog-posts/la-hora-del-planeta-mas-que-apagar-las-luces.source",
      title: "La Hora del Planeta: Más que apagar las luces",
      subtitle: "La eficiencia real no dura una hora: se construye con hábitos operativos, monitoreo y decisiones sostenidas en el tiempo.",
      description: "Descubre cómo transformar el gesto simbólico de La Hora del Planeta en hábitos diarios de eficiencia energética en tu empresa con medidas prácticas y sostenibles.",
      categoryKey: "sostenibilidad",
      publishedAt: "2025-03-28",
      coverImage: "assets/blog/la-hora-del-planeta-mas-que-apagar-las-luces-cover.png",
      coverAlt: "La Hora del Planeta: Más que apagar las luces"
    },
    {
      slug: "primer-trimestre-del-ano-como-medir-y-mejorar-tu-gestion-energetica",
      sourceFile: "content/blog-posts/primer-trimestre-del-ano-como-medir-y-mejorar-tu-gestion-energetica.source",
      title: "Primer trimestre del año: ¿Cómo medir y mejorar tu gestión energética?",
      subtitle: "Revisar consumo, costos y patrones de uso al cierre de marzo ayuda a corregir rápido y decidir mejor el resto del año.",
      description: "Análisis trimestral de gestión energética: mide tu consumo, reduce costos y mejora la eficiencia de tu empresa con estrategias efectivas y herramientas como Clickie.",
      categoryKey: "multisucursal",
      publishedAt: "2025-03-31",
      coverImage: "assets/blog/primer-trimestre-del-ano-como-medir-y-mejorar-tu-gestion-energetica-cover.png",
      coverAlt: "Primer trimestre del año: ¿Cómo medir y mejorar tu gestión energética?"
    },
    {
      slug: "la-energia-dejo-de-ser-un-gasto-conoce-como-la-energy-cloud-te-hace-ganar-control-y-eficiencia",
      sourceFile: "content/blog-posts/la-energia-dejo-de-ser-un-gasto-conoce-como-la-energy-cloud-te-hace-ganar-control-y-eficiencia.source",
      title: "La energía dejó de ser un gasto. Conoce cómo la Energy Cloud te hace ganar control y eficiencia.",
      subtitle: "La digitalización energética está cambiando el rol del usuario y convirtiendo la energía en una variable cada vez más gestionable.",
      description: "Descubre cómo la Energy Cloud transforma la industria energética, empoderando a los usuarios y optimizando el consumo mediante tecnologías avanzadas y energías renovables.",
      categoryKey: "sostenibilidad",
      publishedAt: "2025-04-07",
      coverImage: "assets/blog/la-energia-dejo-de-ser-un-gasto-conoce-como-la-energy-cloud-te-hace-ganar-control-y-eficiencia-cover.jpeg",
      coverAlt: "La energía dejó de ser un gasto. Conoce cómo la Energy Cloud te hace ganar control y eficiencia."
    },
    {
      slug: "los-impulsores-del-cambio-energetico-clientes-mas-exigentes-datos-mas-valiosos-y-un-sistema-mas-descentralizado",
      sourceFile: "content/blog-posts/los-impulsores-del-cambio-energetico-clientes-mas-exigentes-datos-mas-valiosos-y-un-sistema-mas-descentralizado.source",
      title: "Los impulsores del cambio energético: clientes más exigentes, datos más valiosos y un sistema más descentralizado",
      subtitle: "Consumidores más activos, infraestructura distribuida y datos accionables están redefiniendo la forma de gestionar energía.",
      description: "Transformación energética: consumidores informados, datos valiosos y sistemas descentralizados redefinen el sector. ¿Está tu empresa preparada para liderar este cambio? Descubrí más en nuestro blog.",
      categoryKey: "sostenibilidad",
      publishedAt: "2025-04-07",
      coverImage: "assets/blog/los-impulsores-del-cambio-energetico-clientes-mas-exigentes-datos-mas-valiosos-y-un-sistema-mas-descentralizado-cover.jpg",
      coverAlt: "Los impulsores del cambio energético: clientes más exigentes, datos más valiosos y un sistema más descentralizado"
    },
    {
      slug: "nuevo-aumento-en-el-precio-de-la-electricidad-a-partir-de-julio-2025",
      sourceFile: "content/blog-posts/nuevo-aumento-en-el-precio-de-la-electricidad-a-partir-de-julio-2025.source",
      title: "Nuevo aumento en el precio de la electricidad a partir de julio de 2025",
      subtitle: "Cuando suben las tarifas, la diferencia entre absorber el impacto o perder margen suele estar en qué tan bien gestionas el consumo.",
      description: "Nuevo aumento en tarifas eléctricas en julio de 2025. Clickie te ayuda a optimizar tu consumo energético y reducir costos.",
      categoryKey: "industria",
      publishedAt: "2025-04-23",
      coverImage: "assets/blog/nuevo-aumento-en-el-precio-de-la-electricidad-a-partir-de-julio-2025-cover.jpeg",
      coverAlt: "Nuevo aumento en el precio de la electricidad a partir de julio de 2025"
    },
    {
      slug: "como-preparar-tu-tienda-para-ahorrar-energia-este-invierno",
      sourceFile: "content/blog-posts/como-preparar-tu-tienda-para-ahorrar-energia-este-invierno.source",
      title: "¿Cómo preparar tu tienda para ahorrar energía este invierno?",
      subtitle: "Calefacción, iluminación y monitoreo: tres frentes concretos para pasar el invierno con más control y menos desperdicio.",
      description: "Descubre cómo reducir costos de energía en tu tienda este invierno con estrategias prácticas para calefacción eficiente y aprovechamiento de la luz natural. Mejora tu gestión energética hoy mismo.",
      categoryKey: "multisucursal",
      publishedAt: "2025-04-27",
      coverImage: "assets/blog/como-preparar-tu-tienda-para-ahorrar-energia-este-invierno-cover.jpeg",
      coverAlt: "¿Cómo preparar tu tienda para ahorrar energía este invierno?"
    },
    {
      slug: "tienes-datos-de-tu-consumo-de-energia-ahora-usalos-para-tomar-decisiones-reales",
      sourceFile: "content/blog-posts/tienes-datos-de-tu-consumo-de-energia-ahora-usalos-para-tomar-decisiones-reales.source",
      title: "¿Tienes datos de tu consumo de energía? Ahora úsalos para tomar decisiones reales",
      subtitle: "El dato por sí solo no ahorra nada: el valor aparece cuando se traduce en hipótesis, acciones y mejora continua.",
      description: "Optimiza tu consumo energético usando datos reales. Aprende a detectar patrones, tomar decisiones informadas y mejorar continuamente con la ayuda de Clickie.",
      categoryKey: "eficiencia",
      publishedAt: "2025-05-07",
      coverImage: "assets/blog/tienes-datos-de-tu-consumo-de-energia-ahora-usalos-para-tomar-decisiones-reales-cover.jpeg",
      coverAlt: "¿Tienes datos de tu consumo de energía? Ahora úsalos para tomar decisiones reales"
    },
    {
      slug: "sabes-cuanto-impacto-positivo-esta-generando-tu-empresa",
      sourceFile: "content/blog-posts/sabes-cuanto-impacto-positivo-esta-generando-tu-empresa.source",
      title: "¿Sabes cuánto impacto positivo está generando tu empresa?",
      subtitle: "Medir CO2 evitado y otras equivalencias ayuda a convertir el ahorro energético en una historia de sostenibilidad más visible.",
      description: "Descubre cómo medir el impacto positivo de tu ahorro energético traducido en CO2 evitado, árboles salvados y más, impulsando tu estrategia de sostenibilidad.",
      categoryKey: "sostenibilidad",
      publishedAt: "2025-05-15",
      coverImage: "assets/blog/sabes-cuanto-impacto-positivo-esta-generando-tu-empresa-cover.jpeg",
      coverAlt: "¿Sabes cuánto impacto positivo está generando tu empresa?"
    },
    {
      slug: "sabias-que-puedes-usar-tus-datos-del-coordinador-electrico-en-la-plataforma-clickie",
      sourceFile: "content/blog-posts/sabias-que-puedes-usar-tus-datos-del-coordinador-electrico-en-la-plataforma-clickie.source",
      title: "¿Sabías que puedes usar tus datos del Coordinador Eléctrico en la Plataforma Clickie?",
      subtitle: "Si ya eres Cliente Libre, tus datos energéticos pueden integrarse directamente a Clickie y dejar de vivir en planillas o archivos sueltos.",
      description: "Integra automáticamente tus datos del Coordinador Eléctrico Nacional a Clickie y optimiza tu gestión energética sin complicaciones.",
      categoryKey: "eficiencia",
      publishedAt: "2025-06-10",
      coverImage: "assets/blog/sabias-que-puedes-usar-tus-datos-del-coordinador-electrico-en-la-plataforma-clickie-cover.png",
      coverAlt: "¿Sabías que puedes usar tus datos del Coordinador Eléctrico en la Plataforma Clickie?"
    },
    {
      slug: "mide-lo-que-realmente-importa-optimizacion-datos-y-eficiencia-al-alcance-de-tu-linea-de-produccion",
      sourceFile: "content/blog-posts/mide-lo-que-realmente-importa-optimizacion-datos-y-eficiencia-al-alcance-de-tu-linea-de-produccion.source",
      title: "Mide lo que realmente importa: Optimización, datos y eficiencia al alcance de tu línea de producción",
      subtitle: "Cruzar OPI-NONA, OEE y consumo energético permite entender mejor rendimiento, pérdidas y costo operativo en producción.",
      description: "Optimiza tu producción midiendo indicadores clave como OPI-NONA y OEE para mejorar eficiencia, reducir costos y tomar decisiones rápidas basadas en datos reales.",
      categoryKey: "industria",
      publishedAt: "2025-06-16",
      coverImage: "assets/blog/mide-lo-que-realmente-importa-optimizacion-datos-y-eficiencia-al-alcance-de-tu-linea-de-produccion-cover.png",
      coverAlt: "Mide lo que realmente importa: Optimización, datos y eficiencia al alcance de tu línea de producción"
    },
    {
      slug: "energia-datos-y-futuro-clickie-visito-la-expo-osaka-2025",
      sourceFile: "content/blog-posts/energia-datos-y-futuro-clickie-visito-la-expo-osaka-2025.source",
      title: "Energía, datos y futuro: Clickie visitó la Expo Osaka 2025",
      subtitle: "Una visita a Osaka dejó tres señales claras sobre el futuro energético: más automatización, más datos y una sostenibilidad cada vez más tangible.",
      description: "Descubre cómo la Expo Osaka 2025 está moldeando el futuro de la energía y la sostenibilidad con innovaciones de China, Arabia Saudita y Japón.",
      categoryKey: "prensa",
      publishedAt: "2025-06-23",
      coverImage: "assets/blog/energia-datos-y-futuro-clickie-visito-la-expo-osaka-2025-cover.jpeg",
      coverAlt: "Energía, datos y futuro: Clickie visitó la Expo Osaka 2025"
    },
    {
      slug: "clickie-en-la-feria-del-medio-ambiente-de-vulco-tecnologia-sostenibilidad-y-trabajo-conjunto",
      sourceFile: "content/blog-posts/clickie-en-la-feria-del-medio-ambiente-de-vulco-tecnologia-sostenibilidad-y-trabajo-conjunto.source",
      title: "Clickie en la Feria del Medio Ambiente de Vulco: tecnología, sostenibilidad y trabajo conjunto",
      subtitle: "Una jornada para mostrar cómo datos, monitoreo y cultura organizacional pueden convertir sostenibilidad en práctica operativa.",
      description: "Clickie participa en la Feria del Medio Ambiente de Vulco, mostrando cómo su tecnología mejora la eficiencia y sostenibilidad en la gestión energética.",
      categoryKey: "prensa",
      publishedAt: "2025-06-26",
      coverImage: "assets/blog/clickie-en-la-feria-del-medio-ambiente-de-vulco-tecnologia-sostenibilidad-y-trabajo-conjunto-cover.png",
      coverAlt: "Clickie en la Feria del Medio Ambiente de Vulco: tecnología, sostenibilidad y trabajo conjunto"
    },
    {
      slug: "como-se-logran-ahorros-reales-en-locales-como-oxxo-monitoreo-de-energia-en-retail",
      sourceFile: "content/blog-posts/como-se-logran-ahorros-reales-en-locales-como-oxxo-monitoreo-de-energia-en-retail.source",
      title: "¿Cómo se logran ahorros reales en locales como OXXO? Monitoreo de Energía en Retail",
      subtitle: "Monitoreo, control operativo y gestión de facturas se combinan para convertir datos energéticos en mejoras concretas en retail.",
      description: "Descubre cómo OXXO optimiza su consumo eléctrico en Chile con Clickie, a través del monitoreo y control de energía en tiempo real. Ahorros reales y eficiencia energética para el retail.",
      categoryKey: "casos",
      publishedAt: "2025-07-18",
      coverImage: "assets/blog/como-se-logran-ahorros-reales-en-locales-como-oxxo-monitoreo-de-energia-en-retail-cover.jpeg",
      coverAlt: "¿Cómo se logran ahorros reales en locales como OXXO? Monitoreo de Energía en Retail"
    },
    {
      slug: "asi-monitoreamos-la-energia-en-la-industria-que-son-los-gemelos-digitales",
      sourceFile: "content/blog-posts/asi-monitoreamos-la-energia-en-la-industria-que-son-los-gemelos-digitales.source",
      title: "Así monitoreamos la energía en la industria: ¿Qué son los gemelos digitales?",
      subtitle: "Los gemelos digitales permiten leer consumo, alertas y operación de planta dentro de un contexto mucho más útil para decidir.",
      description: "Optimiza el uso de energía en tu planta industrial con gemelos digitales y tableros inteligentes. Descubre cómo Clickie mejora la eficiencia operativa y reduce la huella de carbono.",
      categoryKey: "industria",
      publishedAt: "2025-07-29",
      coverImage: "assets/blog/asi-monitoreamos-la-energia-en-la-industria-que-son-los-gemelos-digitales-cover.png",
      coverAlt: "Así monitoreamos la energía en la industria: ¿Qué son los gemelos digitales?"
    },
    {
      slug: "como-grupo-tattersall-logro-eficiencia-energetica-con-clickie-un-caso-de-exito-en-sostenibilidad",
      sourceFile: "content/blog-posts/como-grupo-tattersall-logro-eficiencia-energetica-con-clickie-un-caso-de-exito-en-sostenibilidad.source",
      title: "Cómo Grupo Tattersall logró eficiencia energética con Clickie: un caso de éxito en sostenibilidad",
      subtitle: "Más visibilidad, menos cargos evitables y una estrategia de control que empezó a escalar dentro de toda la operación.",
      description: "Grupo Tattersall optimizó su eficiencia energética con Clickie, logrando una significativa reducción de costos y mejorando la sostenibilidad en sus operaciones diversificadas.",
      categoryKey: "casos",
      publishedAt: "2025-08-04",
      coverImage: "assets/blog/como-grupo-tattersall-logro-eficiencia-energetica-con-clickie-un-caso-de-exito-en-sostenibilidad-cover.png",
      coverAlt: "Cómo Grupo Tattersall logró eficiencia energética con Clickie: un caso de éxito en sostenibilidad"
    },
    {
      slug: "que-significa-una-inflacion-energetica-de-0-para-las-empresas-en-america-latina",
      sourceFile: "content/blog-posts/que-significa-una-inflacion-energetica-de-0-para-las-empresas-en-america-latina.source",
      title: "¿Qué significa una inflación energética de 0% para las empresas en América Latina?",
      subtitle: "Un promedio regional estable no elimina la necesidad de gestionar consumo: solo hace más visible dónde están las ineficiencias.",
      description: "Inflación energética en 0%: descubre su impacto en empresas de América Latina y cómo aprovechar esta estabilidad para mejorar la eficiencia energética.",
      categoryKey: "industria",
      publishedAt: "2025-08-20",
      coverImage: "assets/blog/que-significa-una-inflacion-energetica-de-0-para-las-empresas-en-america-latina-cover.png",
      coverAlt: "¿Qué significa una inflación energética de 0% para las empresas en América Latina?"
    },
    {
      slug: "caso-exito-oxxo-energia-chile",
      sourceFile: "content/blog-posts/caso-exito-oxxo-energia-chile.source",
      title: "Caso de éxito: Cómo OXXO gestiona la energía de más de 230 tiendas en Chile con Clickie",
      subtitle: "Cómo una operación de más de 230 tiendas convirtió monitoreo, análisis y personalización por local en una palanca real de eficiencia.",
      description: "Caso de éxito: Monitoreo de Energía en Empresas de Chile. OXXO optimiza la energía de más de 230 tiendas en Chile con Clickie, logrando eficiencia y sostenibilidad a través de un monitoreo personalizado.",
      categoryKey: "casos",
      publishedAt: "2025-07-03",
      readingTime: 4,
      coverImage: "assets/blog/caso-exito-oxxo-energia-chile-cover.png",
      coverAlt: "Caso de éxito: Cómo OXXO gestiona la energía de más de 230 tiendas en Chile con Clickie"
    },
    {
      slug: "1-grado-rentabilidad",
      sourceFile: "content/blog-posts/1-grado-rentabilidad.source",
      title: "¿Sabías que 1°C puede definir la rentabilidad de tu tienda este verano?",
      subtitle: "Un ajuste mínimo en climatización puede mover hasta un 8% del gasto mensual y marcar la diferencia entre confort y desperdicio.",
      description: "La climatización puede representar entre el 40% y 60% del consumo total. Un ajuste de 1°C puede significar hasta un 8% de ahorro.",
      categoryKey: "multisucursal",
      publishedAt: "2025-11-28",
      readingTime: 4,
      coverImage: "assets/blog-1grado.jpg",
      coverAlt: "Sistema de aire acondicionado en operación comercial"
    },
    {
      slug: "starbucks-clickie",
      sourceFile: "content/blog-posts/starbucks-clickie.source",
      title: "Starbucks ahorra energía junto a Clickie",
      subtitle: "Un caso real de monitoreo y acompañamiento experto para transformar consumo energético en ahorro medible dentro de una operación multisucursal.",
      description: "Conoce cómo Starbucks transformó su consumo energético en ahorro real con monitoreo en tiempo real y acompañamiento de Clickie.",
      categoryKey: "casos",
      publishedAt: "2025-11-25",
      readingTime: 4,
      coverImage: "assets/blog-starbucks.png",
      coverAlt: "Operación Starbucks con enfoque en eficiencia energética"
    },
    {
      slug: "transicion-energetica",
      sourceFile: "content/blog-posts/transicion-energetica.source",
      title: "La transición energética como oportunidad de crecimiento",
      subtitle: "La sostenibilidad ya no es solo cumplimiento: bien gestionada, se convierte en una fuente de competitividad y expansión.",
      description: "La transición energética ya no es solo una meta ambiental: se ha convertido en una palanca de valor para las empresas.",
      categoryKey: "sostenibilidad",
      publishedAt: "2025-10-08",
      readingTime: 4,
      coverImage: "assets/blog-transicion.png",
      coverAlt: "Representación visual de transición energética y sostenibilidad"
    },
    {
      slug: "como-ayuda-clickie",
      sourceFile: "content/blog-posts/como-ayuda-clickie.source",
      title: "Paso a paso: ¿Cómo ayuda Clickie a las empresas a gestionar mejor su energía?",
      subtitle: "Desde monitoreo en tiempo real hasta acciones concretas: así se convierte la data en eficiencia operativa y ahorro sostenido.",
      description: "Descubre el proceso completo de gestión energética con Clickie: monitoreo en tiempo real, identificación de ahorros y acciones concretas.",
      categoryKey: "eficiencia",
      publishedAt: "2025-09-30",
      readingTime: 5,
      coverImage: "assets/blog-como-ayuda.png",
      coverAlt: "Ilustración de gestión energética empresarial con Clickie"
    },
    {
      slug: "clickie-el-mercurio",
      sourceFile: "content/blog-posts/clickie-el-mercurio.source",
      title: "Clickie en El Mercurio: startup que permite ahorrar hasta 20% en la cuenta de la luz",
      subtitle: "Cobertura de prensa sobre cómo Clickie ayuda a empresas a reducir consumo, visibilizar desvíos y operar con mayor control.",
      description: "El Mercurio destaca a Clickie como la startup que ayuda a las empresas a ahorrar hasta un 20% en su cuenta de electricidad.",
      categoryKey: "prensa",
      publishedAt: "2025-09-30",
      readingTime: 5,
      coverImage: "assets/blog-el-mercurio.png",
      coverAlt: "Cobertura de prensa de Clickie en El Mercurio"
    },
    {
      slug: "la-araucana-co2",
      sourceFile: "content/blog-posts/la-araucana-co2.source",
      title: "Cómo La Araucana redujo su huella de carbono un 14% con Clickie",
      subtitle: "Monitoreo flexible, alertas y acompañamiento estratégico para convertir metas ambientales en resultados medibles.",
      description: "La Araucana implementó monitoreo inteligente con Clickie y logró reducir su huella de carbono un 14%, superando su meta del 10%.",
      categoryKey: "casos",
      publishedAt: "2025-09-22",
      readingTime: 5,
      coverImage: "assets/blog-la-araucana.png",
      coverAlt: "Caso de éxito de La Araucana junto a Clickie"
    },
    {
      slug: "transformar-datos-en-ahorros-asi-reduces-tus-costos-energeticos",
      sourceFile: "content/blog-posts/transformar-datos-en-ahorros-asi-reduces-tus-costos-energeticos.source",
      title: "Transformar datos en ahorros: así reduces tus costos energéticos",
      subtitle: "Medir sirve poco si no se traduce en decisiones operativas; el ahorro aparece cuando los datos se convierten en acción.",
      description: "Los datos energéticos solo generan valor cuando se convierten en decisiones. Descubre cómo pasar de medición a ahorro real.",
      categoryKey: "eficiencia",
      publishedAt: "2025-09-08",
      coverImage: "assets/blog/transformar-datos-en-ahorros-asi-reduces-tus-costos-energeticos-cover.png",
      coverAlt: "Transformar datos en ahorros: así reduces tus costos energéticos"
    },
    {
      slug: "datos-en-ahorros",
      sourceFile: "content/blog-posts/datos-en-ahorros.source",
      title: "Cómo en Clickie convertimos datos en ahorros de energía",
      subtitle: "Tener datos no basta: el valor aparece cuando se traducen en alertas, decisiones y acciones concretas dentro de la operación.",
      description: "Los datos por sí solos no sirven. Descubre cómo Clickie transforma millones de datos en acciones concretas que generan ahorros reales.",
      categoryKey: "eficiencia",
      publishedAt: "2025-09-10",
      readingTime: 5,
      coverImage: "assets/blog-datos-ahorros.png",
      coverAlt: "Visualización de datos energéticos orientados a ahorro"
    },
    {
      slug: "edificios-una-oportunidad-para-reducir-la-demanda-energetica-global",
      sourceFile: "content/blog-posts/edificios-una-oportunidad-para-reducir-la-demanda-energetica-global.source",
      title: "Edificios: Una Oportunidad para Reducir la Demanda Energética Global",
      subtitle: "La digitalización y las intervenciones específicas en edificios pueden reducir intensidad energética, costos operativos y emisiones a escala global.",
      description: "Descubre cómo la gestión energética digitalizada y mejoras en edificios pueden reducir consumo, costos y emisiones en operaciones complejas.",
      categoryKey: "sostenibilidad",
      publishedAt: "2024-07-26",
      coverImage: "assets/blog/edificios-una-oportunidad-para-reducir-la-demanda-energetica-global-cover.jpg"
    },
    {
      slug: "edificios-verdes-y-monitoreo-de-energia-con-clickie",
      sourceFile: "content/blog-posts/edificios-verdes-y-monitoreo-de-energia-con-clickie.source",
      title: "Edificios Verdes y Monitoreo de Energía con Clickie",
      subtitle: "Diseño verde, monitoreo energético y datos en tiempo real: una combinación clave para reducir costos y hacer más sostenibles los edificios.",
      description: "Explora cómo los edificios verdes y el monitoreo energético ayudan a reducir costos operativos, mejorar eficiencia y acelerar la transición sostenible.",
      categoryKey: "sostenibilidad",
      publishedAt: "2024-09-23",
      coverImage: "assets/blog/edificios-verdes-y-monitoreo-de-energia-con-clickie-cover.jpg"
    },
    {
      slug: "el-impacto-del-aumento-de-tarifas-de-energia-electrica-en-chile",
      sourceFile: "content/blog-posts/el-impacto-del-aumento-de-tarifas-de-energia-electrica-en-chile.source",
      title: "El Impacto del Aumento de Tarifas de Energía Eléctrica en Chile",
      subtitle: "El alza de tarifas no solo aumenta costos: obliga a las empresas a entender mejor su consumo y adaptarse con gestión energética activa.",
      description: "Analiza cómo el aumento de tarifas eléctricas en Chile impacta la operación de las empresas y qué acciones ayudan a absorber mejor el cambio.",
      categoryKey: "industria",
      publishedAt: "2024-09-23",
      coverImage: "assets/blog/el-impacto-del-aumento-de-tarifas-de-energia-electrica-en-chile-cover.png"
    },
    {
      slug: "el-rol-del-gestor-energetico-clave-para-la-eficiencia-y-sostenibilidad-empresarial",
      sourceFile: "content/blog-posts/el-rol-del-gestor-energetico-clave-para-la-eficiencia-y-sostenibilidad-empresarial.source",
      title: "El Rol del Gestor Energético: Clave para la Eficiencia y Sostenibilidad Empresarial",
      subtitle: "Un gestor energético convierte consumo, eficiencia y cumplimiento en una práctica continua dentro de la empresa, no en una reacción aislada.",
      description: "Conoce por qué el rol del gestor energético es clave para reducir desperdicios, mejorar eficiencia y sostener una estrategia empresarial responsable.",
      categoryKey: "eficiencia",
      publishedAt: "2024-10-03",
      coverImage: "assets/blog/el-rol-del-gestor-energetico-clave-para-la-eficiencia-y-sostenibilidad-empresarial-cover.png"
    },
    {
      slug: "piloto-de-avion-y-no-medico-forense-la-diferencia-de-hacer-gestion-energetica-con-datos-pasados-vs-datos-en-linea",
      sourceFile: "content/blog-posts/piloto-de-avion-y-no-medico-forense-la-diferencia-de-hacer-gestion-energetica-con-datos-pasados-vs-datos-en-linea.source",
      title: "Piloto de Avión y No Médico Forense: La Diferencia de Hacer Gestión Energética con Datos Pasados vs. Datos en Línea",
      subtitle: "Trabajar con datos históricos explica lo que pasó; operar con datos en línea permite corregir desvíos mientras todavía hay margen de acción.",
      description: "Una comparación clara entre gestión reactiva y monitoreo en tiempo real para entender por qué los datos en línea cambian la toma de decisiones.",
      categoryKey: "eficiencia",
      publishedAt: "2024-10-03",
      coverImage: "assets/blog/piloto-de-avion-y-no-medico-forense-la-diferencia-de-hacer-gestion-energetica-con-datos-pasados-vs-datos-en-linea-cover.png"
    },
    {
      slug: "potencia-tu-empresa-con-clickie-una-solucion-integral-para-la-gestion-energetica",
      sourceFile: "content/blog-posts/potencia-tu-empresa-con-clickie-una-solucion-integral-para-la-gestion-energetica.source",
      title: "Potencia tu Empresa con Clickie: Una Solución Integral para la Gestión Energética",
      subtitle: "Operaciones, mantenimiento, finanzas y sostenibilidad pueden trabajar sobre una misma base energética cuando la información está bien conectada.",
      description: "Descubre cómo una solución integral de gestión energética ayuda a mejorar operaciones, mantenimiento, finanzas y sostenibilidad en una sola plataforma.",
      categoryKey: "eficiencia",
      publishedAt: "2024-10-03",
      coverImage: "assets/blog/potencia-tu-empresa-con-clickie-una-solucion-integral-para-la-gestion-energetica-cover.jpg"
    }
  ]
};
